apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: no-dejs 
  janus-idp.io/tekton: no-dejs
  backstage.io/kubernetes-id: no-dejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: no-dejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  