apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: no-dejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: no-dejs 
  name: no-dejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: no-dejs
    weight: 100 
